# Generated by Django 2.2 on 2022-03-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleHeatMap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.IntegerField(default=20220301),
        ),
    ]
