# Generated by Django 2.2 on 2022-03-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleHeatMap', '0002_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashkey',
            field=models.IntegerField(default=-1),
        ),
    ]
